kind: ConfigMap
apiVersion: v1
metadata:
  name: vue-configmap
  namespace: default
  labels:
    app: vue-ddd-trade
data:
  default.conf: |-
    server {
      listen       80;
      server_name  localhost;

      location / {
          root   /app;
          index  index.html index.htm;
      }

      location /api {
        add_header 'Access-Control-Allow-Origin' '*';
        rewrite /api/(.*) /$1 break;
        proxy_pass http://edev-trade-gateway:9009;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: vue-ddd-trade
  name: vue-ddd-trade
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-ddd-trade
  template:
    metadata:
      name: vue-ddd-trade
      labels:
        app: vue-ddd-trade
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - vue-ddd-trade
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: vue-ddd-trade
        image: repository:5000/vue-ddd-trade
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: config
        configMap:
          name: vue-configmap
          items:
          - key: default.conf
            path: default.conf
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: vue-ddd-trade
  name: vue-ddd-trade
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vue-ddd-trade
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-edev-vue
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: vue
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-ddd-trade
                port:
                  number: 80